codestates-seb/seb45_main_014

src/main/java/com/main/bbangbbang/menu/controller/MenuController.java, src/main/java/com/main/bbangbbang/menu/dto/MenuResponseDto.java, src/main/java/com/main/bbangbbang/menu/entity/Menu.java, src/main/java/com/main/bbangbbang/menu/entity/MenuEntity.java, src/main/java/com/main/bbangbbang/menu/mapper/MenuMapper.java, src/main/java/com/main/bbangbbang/menu/repository/MenuRepository.java, src/main/java/com/main/bbangbbang/menu/service/MenuService.java
=> ✨menu 기본 구조 구현

src/main/java/com/main/bbangbbang/BbangbbangApplication.java, src/main/java/com/main/bbangbbang/member/entity/Member.java, src/main/java/com/main/bbangbbang/menu/controller/MenuController.java, src/main/java/com/main/bbangbbang/menu/data/MenuBriefData.java, src/main/java/com/main/bbangbbang/menu/data/MenuData.java, src/main/java/com/main/bbangbbang/menu/data/MenuDetailData.java, src/main/java/com/main/bbangbbang/menu/dto/MenuResponseDto.java, src/main/java/com/main/bbangbbang/menu/entity/Menu.java, src/main/java/com/main/bbangbbang/menu/mapper/MenuMapper.java, src/main/java/com/main/bbangbbang/menu/service/MenuService.java
✨Menu package 리팩토링 및 Data 기능 추가
✨Member Entity 추가
=> ✨Menu package 리팩토링 및 Data 기능 추가 외 1건

src/main/java/com/main/bbangbbang/store/controller/StoreController.java, src/main/java/com/main/bbangbbang/store/data/StoreBriefData.java, src/main/java/com/main/bbangbbang/store/data/StoreData.java, src/main/java/com/main/bbangbbang/store/data/StoreDetailData.java, src/main/java/com/main/bbangbbang/store/dto/StoreResponseDto.java, src/main/java/com/main/bbangbbang/store/dto/StoresResponseDto.java, src/main/java/com/main/bbangbbang/store/entity/Store.java, src/main/java/com/main/bbangbbang/store/mapper/StoreMapper.java, src/main/java/com/main/bbangbbang/store/repository/StoreRepository.java, src/main/java/com/main/bbangbbang/store/service/StoreService.java
=> ✨Store 관련 API 구현

src/main/java/com/main/bbangbbang/order/controller/OrderController.java, src/main/java/com/main/bbangbbang/order/data/OrderData.java, src/main/java/com/main/bbangbbang/order/dto/OrderResponseDto.java, src/main/java/com/main/bbangbbang/order/dto/OrdersResponseDto.java, src/main/java/com/main/bbangbbang/order/entity/Order.java, src/main/java/com/main/bbangbbang/order/mapper/OrderMapper.java, src/main/java/com/main/bbangbbang/order/repository/OrderRepository.java, src/main/java/com/main/bbangbbang/order/service/OrderService.java
=> ✨Order API 구현

src/main/java/com/main/bbangbbang/order/controller/OrderController.java, src/main/java/com/main/bbangbbang/order/entity/Order.java, src/main/java/com/main/bbangbbang/order/mapper/OrderMapper.java, src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/region/entity/Region.java, src/main/java/com/main/bbangbbang/region/repository/RegionRepository.java, src/main/java/com/main/bbangbbang/region/service/RegionService.java
✨OrderMenu 관련 메소드 구현 및 Region 패키지 생성
=> ✨OrderMenu 관련 메소드 구현 및 Region 패키지 생성

src/main/java/com/main/bbangbbang/menu/repository/MenuRepository.java, src/main/java/com/main/bbangbbang/menu/service/MenuService.java, src/main/java/com/main/bbangbbang/review/controller/ReviewController.java, src/main/java/com/main/bbangbbang/review/data/ReviewData.java, src/main/java/com/main/bbangbbang/review/data/ReviewDataWithNickname.java, src/main/java/com/main/bbangbbang/review/data/ReviewDataWithStoreName.java, src/main/java/com/main/bbangbbang/review/dto/ReviewsResponseDto.java, src/main/java/com/main/bbangbbang/review/entity/Review.java, src/main/java/com/main/bbangbbang/review/mapper/ReviewMapper.java, src/main/java/com/main/bbangbbang/review/repository/ReviewRepository.java, src/main/java/com/main/bbangbbang/review/service/ReviewService.java, src/main/java/com/main/bbangbbang/search/controller/SearchController.java, src/main/java/com/main/bbangbbang/search/service/SearchService.java, src/main/java/com/main/bbangbbang/store/controller/StoreController.java
=> ✨Search, Review api 구현

src/main/java/com/main/bbangbbang/menu/controller/MenuController.java, src/main/java/com/main/bbangbbang/menu/dto/MenuResponseDto.java, src/main/java/com/main/bbangbbang/menu/mapper/MenuMapper.java, src/main/java/com/main/bbangbbang/menu/service/MenuService.java
=> 💡 필요 없는 주석 삭제

src/main/java/com/main/bbangbbang/order/mapper/OrderMapper.java, src/main/java/com/main/bbangbbang/store/controller/StoreController.java, src/main/java/com/main/bbangbbang/store/mapper/StoreMapper.java, src/main/java/com/main/bbangbbang/utils/PageInfo.java
=> 🐛버그 수정(response 데이터 오류)

src/main/java/com/main/bbangbbang/member/entity/Member.java, src/main/java/com/main/bbangbbang/memberstore/controller/MemberStoreController.java, src/main/java/com/main/bbangbbang/memberstore/data/MemberStoreData.java, src/main/java/com/main/bbangbbang/memberstore/dto/MemberStoreResponseDto.java, src/main/java/com/main/bbangbbang/memberstore/entity/MemberStore.java, src/main/java/com/main/bbangbbang/memberstore/mapper/MemberStoreMapper.java, src/main/java/com/main/bbangbbang/memberstore/repository/MemberStoreRepository.java, src/main/java/com/main/bbangbbang/memberstore/service/MemberStoreService.java, src/main/java/com/main/bbangbbang/store/mapper/StoreMapper.java
=> ✨MemberStore 기능 추가(즐겨찾기)

client/.babelrc, client/src/components/store/MenuTab.jsx, client/src/components/store/ShopInfo.jsx, client/src/components/store/StoreReviewTab.jsx, client/src/pages/Store.jsx, client/src/store/store.js
매장 상세 페이지 서버 연결
페이지 네이션 버튼 및 기능 구현(데이터 부족으로 확인 불가)
장바구니 담기 버튼 (500에러)
=> ✨ 매장 상세페이지 서버 연결, 페이지네이션, 장바구니 담기 버튼

client/src/App.jsx, client/src/components/header/SearchBar.jsx, client/src/pages/Store.jsx, client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx, client/src/pages/search/SearchResult.jsx, client/src/store/store.js
=> ✨ [FE] 검색 페이지, 장바구니 페이지 API 연결

src/main/java/com/main/bbangbbang/auth/handler/OAuth2LoginSuccessHandler.java
사용자가 로그인 성공 시 프론트엔드 페이지로 안내되기 위한 수정 내용입니다.
=> :sparkles:  로그인 성공 후 리다이렉트 URI를 프론트엔드 서버 3000 포트로 변경

src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/review/controller/ReviewController.java, src/main/java/com/main/bbangbbang/review/dto/ReviewResponseDto.java, src/main/java/com/main/bbangbbang/review/repository/ReviewRepository.java, src/main/java/com/main/bbangbbang/review/service/ReviewService.java
=> ✨Review api 구현

src/main/java/com/main/bbangbbang/menu/data/MenuSearchData.java, src/main/java/com/main/bbangbbang/menu/dto/MenusResponseDto.java, src/main/java/com/main/bbangbbang/menu/mapper/MenuMapper.java, src/main/java/com/main/bbangbbang/order/controller/OrderController.java, src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/ordermenu/data/OrderMenuData.java, src/main/java/com/main/bbangbbang/ordermenu/mapper/OrderMenuMapper.java, src/main/java/com/main/bbangbbang/region/repository/RegionRepository.java, src/main/java/com/main/bbangbbang/region/service/RegionService.java, src/main/java/com/main/bbangbbang/search/controller/SearchController.java, src/main/java/com/main/bbangbbang/search/service/SearchService.java
=> ✨검색 사양 변경 및 일부 버그 수정

src/main/java/com/main/bbangbbang/auth/config/SecurityConfiguration.java, src/main/java/com/main/bbangbbang/auth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/main/bbangbbang/member/controller/MemberController.java, src/main/java/com/main/bbangbbang/member/dto/requestDto/MemberPatchDto.java, src/main/java/com/main/bbangbbang/member/dto/requestDto/MemberPostDto.java, src/main/java/com/main/bbangbbang/member/dto/responseDto/MemberResponseDto.java, src/main/java/com/main/bbangbbang/member/mapper/MemberMapper.java, src/main/java/com/main/bbangbbang/member/service/MemberService.java
- 검증된 유저 생성 후 리다이렉트 시 정보 받아와서 저장 (Member 등록)
- Member CRUD 구현
- h2와 포스트맨으로 조회, 수정, 삭제 테스트 완료했습니다.
=> ✨ JWT + OAuth2 유저 -> Member 로 회원관리 기능 구현 

src/main/java/com/main/bbangbbang/auth/handler/OAuth2LoginSuccessHandler.java
:bug:  createURI() 메서드 사용하여 토큰 -> 쿼리파람으로 보내도록 코드 변경
=> :bug:  createURI() 메서드 사용하여 토큰 -> 쿼리파람으로 보내도록 코드 변경

src/main/java/com/main/bbangbbang/exception/ExceptionCode.java, src/main/java/com/main/bbangbbang/member/service/MemberService.java, src/main/java/com/main/bbangbbang/memberstore/controller/MemberStoreController.java, src/main/java/com/main/bbangbbang/order/controller/OrderController.java, src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/review/controller/ReviewController.java
=> 🐛Order/MemberStore API 코드 수정

src/main/java/com/main/bbangbbang/store/controller/StoreController.java, src/main/java/com/main/bbangbbang/store/service/StoreService.java
메인 페이지의 가게를 pagination하여 return
(현재는 id순이나 이후 특정 순서로 출력되게 변경 가능)
=> ✨메인 페이지 가게 목록 API 기능 구현

src/main/java/com/main/bbangbbang/exception/ExceptionCode.java, src/main/java/com/main/bbangbbang/ordermenu/controller/OrderMenuController.java, src/main/java/com/main/bbangbbang/ordermenu/repository/OrderMenuRepository.java, src/main/java/com/main/bbangbbang/ordermenu/service/OrderMenuService.java
member의 Active Order에 대해 확인한 뒤, order 안의 ordermenu 제거 transaction 처리하여 도중 오류 시 삭제 전체 취소
=> ✨주문에 대한 각 Item을 삭제하는 API 추가

client/src/App.jsx, client/src/assets/Dropdown.jsx, client/src/assets/StoreCard.jsx, client/src/components/header/DropdownMenu.jsx, client/src/components/header/Greeting.jsx, client/src/components/header/Header.jsx, client/src/components/header/SearchBar.jsx, client/src/components/header/Usermenu.jsx, client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx, client/src/pages/cart/SubmitModal.jsx, client/src/pages/main/MainPage.jsx, client/src/pages/search/SearchResult.jsx
회원 로그인 시 메뉴 조건부 렌더링 추가
유저메뉴 옆에 회원 닉네임 노출
=> ✨ 회원 로그인 정보 Header에 노출되는 기능 구현

src/main/java/com/main/bbangbbang/exception/BusinessLogicException.java, src/main/java/com/main/bbangbbang/exception/ExceptionCode.java, src/main/java/com/main/bbangbbang/menu/data/MenuData.java, src/main/java/com/main/bbangbbang/menu/data/MenuDetailData.java, src/main/java/com/main/bbangbbang/menu/service/MenuService.java, src/main/java/com/main/bbangbbang/order/controller/OrderController.java, src/main/java/com/main/bbangbbang/order/entity/Order.java, src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/review/controller/ReviewController.java, src/main/java/com/main/bbangbbang/review/service/ReviewService.java
♻코드 리팩토링 및 각종 버그 수정
자세한 내용은 commit 참조
=> ♻코드 리팩토링 및 각종 버그 수정

build.gradle, src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/review/controller/ReviewController.java, src/main/java/com/main/bbangbbang/review/entity/Review.java, src/main/java/com/main/bbangbbang/review/service/ReviewService.java, src/main/java/com/main/bbangbbang/s3/S3Config.java, src/main/java/com/main/bbangbbang/s3/S3Service.java, src/main/resources/application.yml
=> ✨리뷰 이미지 업로드 기능 추가

client/src/App.jsx, client/src/api/cart.js, client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx, client/src/store/store.js
선택 삭제 기능 구현
아이템에 해당하는 매장으로 이동하는 기능 구현
주문 기능 구현(100%는 아닌 듯)
=> ✨ 장바구니 선택삭제 기능, 주문기능 추가

client/public/index.html, client/src/components/store/ShopInfo.1.jsx, client/src/components/store/modal/FalseModal.jsx, client/src/pages/Store.jsx
지도 API 입력된 주소에 해당하는 좌표로 브라우저에 출력
=> ✨ 지도 API 주소 > 좌표 이동하게 수정

src/main/java/com/main/bbangbbang/memberstore/controller/MemberStoreController.java, src/main/java/com/main/bbangbbang/memberstore/data/MemberStoreDetailData.java, src/main/java/com/main/bbangbbang/memberstore/dto/MemberStoresResponseDto.java, src/main/java/com/main/bbangbbang/memberstore/mapper/MemberStoreMapper.java, src/main/java/com/main/bbangbbang/memberstore/repository/MemberStoreRepository.java, src/main/java/com/main/bbangbbang/memberstore/service/MemberStoreService.java, src/main/java/com/main/bbangbbang/menu/controller/MenuController.java, src/main/java/com/main/bbangbbang/order/controller/OrderController.java, src/main/java/com/main/bbangbbang/order/repository/OrderRepository.java, src/main/java/com/main/bbangbbang/order/service/OrderService.java, src/main/java/com/main/bbangbbang/ordermenu/controller/OrderMenuController.java, src/main/java/com/main/bbangbbang/search/service/SearchService.java
=> ✨마이페이지 즐겨찾기 기능 구현 및 주문 기능 수정

src/main/java/com/main/bbangbbang/review/controller/ReviewController.java, src/main/java/com/main/bbangbbang/review/dto/ReviewRequestDto.java, src/main/java/com/main/bbangbbang/review/service/ReviewService.java
=> ✨ReviewRequestDto 클래스 추가

client/package-lock.json, client/package.json, client/src/App.css, client/src/App.jsx, client/src/api/cart.js, client/src/assets/StoreCard.jsx, client/src/assets/styles/GlobalStyle.jsx, client/src/index.js, client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx
추가한 장바구니 기능
- 메뉴 개수 변경(해당 item의 id로 stock을 불러와서 stock을 초과하려 할 경우 경고 팝업)
- 아이템 박스의 X버튼으로 삭제 가능
- 장바구니에 아이템이 없을 경우의 렌더링 추가
- ~~픽업시간 안내~~ (마이페이지로 이동하도록 변경해서 삭제함)
=> ✨ [FE] 장바구니 기능 추가, react-hot-toast 적용

client/src/App.css, client/src/api/cart.js, client/src/assets/Modal.jsx, client/src/assets/styles/GlobalStyle.jsx, client/src/components/header/Header.jsx, client/src/components/header/Usermenu.jsx, client/src/components/store/MenuTab.jsx, client/src/components/store/modal/FalseModal.jsx, client/src/components/store/modal/MenuModal.jsx, client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx, client/src/pages/cart/SubmitModal.jsx, client/src/store/store.js
최종 모달 담기 클릭 후 모든 모달이 닫히도록 수정
로그아웃 API 연결
헤더 장바구니 배지 개수가 다르게 보이는 현상 수정
=> ✨ [FE] 상점 페이지 모달 컴포넌트 수정, 로그아웃 연결

client/src/components/header/DropdownMenu.jsx, client/src/components/header/Header.jsx, client/src/components/header/SearchBar.jsx, client/src/components/header/SearchDropdown.jsx
검색어를 Localstorage에 저장 후 최근 검색어를 노출
최근 검색어를 클릭하면 검색창에 반영되도록 구현
=> ✨ [FE] 검색어 저장 기능 추가

client/src/components/header/SearchBar.jsx, client/src/components/header/SearchDropdown.jsx
[상태변경 이전의 query, target으로 이동하는 문제 수정](https://github.com/codestates-seb/seb45_main_014/commit/8d014607ec5f5293b6539dde5b71c95593b13b05)
=> 🐛 [FE] 검색창 오류 수정

client/src/api/cart.js, client/src/components/header/Header.jsx, client/src/components/header/Usermenu.jsx, client/src/pages/Store.jsx, client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx
=> ✨ [FE] 유저 이미지 추가

client/src/pages/cart/Cart.jsx, client/src/pages/cart/CartItem.jsx
=> ✨ 장바구니 메뉴 수량이 바뀔때마다 업데이트하도록 변경
